name: CI

on: [push, pull_request]

env:
  SRB_SKIP_GEM_RBIS: true

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby: [ 2.6, 2.7, 3.0 ]
        bundler: [ 2.2.22, 2.2.25 ]
    name: Test Ruby ${{ matrix.ruby }}, Bundler ${{ matrix.bundler }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler: ${{ matrix.bundler }}
          bundler-cache: true
      - name: Run tests
        env:
          BUNDLER_VERSION: ${{matrix.bundler}}
        run: bin/test
